// Copyright 2020 Fortinet, Inc. All rights reserved.
// Author: Hongbin Lu (@fgtdev-hblu), Frank Shen (@frankshen01)
// Documentation:
// Hongbin Lu (@fgtdev-hblu), Frank Shen (@frankshen01),
// Xing Li (@lix-fortinet), Yue Wang (@yuew-ftnt)

// Description: Provider for FortiManager

package fortimanager

import (
	"github.com/hashicorp/terraform-plugin-sdk/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/helper/validation"
	"github.com/hashicorp/terraform-plugin-sdk/terraform"
)

// Provider creates and returns the FortiManager terraform.ResourceProvider
func Provider() terraform.ResourceProvider {
	return &schema.Provider{
		Schema: map[string]*schema.Schema{
			"hostname": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "The hostname/IP address of the FORTIMANAGER to be connected",
			},

			"username": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "",
			},

			"password": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "",
			},

			"insecure": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "",
			},

			"cabundlefile": {
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "CA Bundle file",
			},

			"scopetype": &schema.Schema{
				Type:     schema.TypeString,
				Optional: true,
				Default:  "adom",
				ValidateFunc: validation.StringInSlice([]string{
					"adom",
					"global",
				}, false),
			},

			"adom": &schema.Schema{
				Type:     schema.TypeString,
				Optional: true,
				Default:  "root",
			},
		},

		ResourcesMap: map[string]*schema.Resource{
			//"fortimanager_json_rpc_request":                     resourceJSONRPCRequest(),
			"fortimanager_exec_workspace_action": resourceExecWorkspaceAction(),

			"fortimanager_packages_firewall_policy_move":                             resourcePackagesFirewallPolicyMove(),
			"fortimanager_packages_firewall_multicastpolicy_move":                    resourcePackagesFirewallMulticastPolicyMove(),
			"fortimanager_packages_firewall_interfacepolicy_move":                    resourcePackagesFirewallInterfacePolicyMove(),
			"fortimanager_packages_firewall_interfacepolicy6_move":                   resourcePackagesFirewallInterfacePolicy6Move(),
			"fortimanager_packages_firewall_localinpolicy_move":                      resourcePackagesFirewallLocalInPolicyMove(),
			"fortimanager_packages_firewall_localinpolicy6_move":                     resourcePackagesFirewallLocalInPolicy6Move(),
			"fortimanager_packages_firewall_policy64_move":                           resourcePackagesFirewallPolicy64Move(),
			"fortimanager_packages_firewall_dospolicy_move":                          resourcePackagesFirewallDosPolicyMove(),
			"fortimanager_packages_firewall_policy46_move":                           resourcePackagesFirewallPolicy46Move(),
			"fortimanager_packages_firewall_dospolicy6_move":                         resourcePackagesFirewallDosPolicy6Move(),
			"fortimanager_packages_firewall_shapingpolicy_move":                      resourcePackagesFirewallShapingPolicyMove(),
			"fortimanager_packages_firewall_multicastpolicy6_move":                   resourcePackagesFirewallMulticastPolicy6Move(),
			"fortimanager_packages_firewall_centralsnatmap_move":                     resourcePackagesFirewallCentralSnatMapMove(),
			"fortimanager_packages_firewall_proxypolicy_move":                        resourcePackagesFirewallProxyPolicyMove(),
			"fortimanager_packages_firewall_securitypolicy_move":                     resourcePackagesFirewallSecurityPolicyMove(),
			"fortimanager_packages_pkg":                                              resourcePackagesPkg(),
			"fortimanager_packages_firewall_policy":                                  resourcePackagesFirewallPolicy(),
			"fortimanager_packages_global_header_policy":                             resourcePackagesGlobalHeaderPolicy(),
			"fortimanager_packages_global_footer_policy":                             resourcePackagesGlobalFooterPolicy(),
			"fortimanager_packages_global_header_policy6":                            resourcePackagesGlobalHeaderPolicy6(),
			"fortimanager_packages_global_footer_policy6":                            resourcePackagesGlobalFooterPolicy6(),
			"fortimanager_packages_firewall_multicastpolicy":                         resourcePackagesFirewallMulticastPolicy(),
			"fortimanager_packages_firewall_interfacepolicy":                         resourcePackagesFirewallInterfacePolicy(),
			"fortimanager_packages_firewall_interfacepolicy6":                        resourcePackagesFirewallInterfacePolicy6(),
			"fortimanager_packages_firewall_localinpolicy":                           resourcePackagesFirewallLocalInPolicy(),
			"fortimanager_packages_firewall_localinpolicy6":                          resourcePackagesFirewallLocalInPolicy6(),
			"fortimanager_packages_firewall_policy64":                                resourcePackagesFirewallPolicy64(),
			"fortimanager_packages_firewall_dospolicy":                               resourcePackagesFirewallDosPolicy(),
			"fortimanager_packages_firewall_policy46":                                resourcePackagesFirewallPolicy46(),
			"fortimanager_packages_firewall_dospolicy6":                              resourcePackagesFirewallDosPolicy6(),
			"fortimanager_packages_firewall_shapingpolicy":                           resourcePackagesFirewallShapingPolicy(),
			"fortimanager_packages_global_header_shapingpolicy":                      resourcePackagesGlobalHeaderShapingPolicy(),
			"fortimanager_packages_global_footer_shapingpolicy":                      resourcePackagesGlobalFooterShapingPolicy(),
			"fortimanager_packages_firewall_multicastpolicy6":                        resourcePackagesFirewallMulticastPolicy6(),
			"fortimanager_packages_firewall_centralsnatmap":                          resourcePackagesFirewallCentralSnatMap(),
			"fortimanager_packages_firewall_proxypolicy":                             resourcePackagesFirewallProxyPolicy(),
			"fortimanager_packages_authentication_rule":                              resourcePackagesAuthenticationRule(),
			"fortimanager_packages_authentication_setting":                           resourcePackagesAuthenticationSetting(),
			"fortimanager_packages_global_header_consolidated_policy":                resourcePackagesGlobalHeaderConsolidatedPolicy(),
			"fortimanager_packages_global_footer_consolidated_policy":                resourcePackagesGlobalFooterConsolidatedPolicy(),
			"fortimanager_packages_firewall_securitypolicy":                          resourcePackagesFirewallSecurityPolicy(),
			"fortimanager_dvmdb_script_execute":                                      resourceDvmdbScriptExecute(),
			"fortimanager_dvm_cmd_add_device":                                        resourceDvmCmdAddDevice(),
			"fortimanager_dvm_cmd_add_devlist":                                       resourceDvmCmdAddDevList(),
			"fortimanager_dvm_cmd_discover_device":                                   resourceDvmCmdDiscoverDevice(),
			"fortimanager_dvm_cmd_update_device":                                     resourceDvmCmdUpdateDevice(),
			"fortimanager_dvm_cmd_update_devlist":                                    resourceDvmCmdUpdateDevList(),
			"fortimanager_dvm_cmd_reload_devlist":                                    resourceDvmCmdReloadDevList(),
			"fortimanager_dvm_cmd_del_device":                                        resourceDvmCmdDelDevice(),
			"fortimanager_dvm_cmd_del_devlist":                                       resourceDvmCmdDelDevList(),
			"fortimanager_securityconsole_abort":                                     resourceSecurityconsoleAbort(),
			"fortimanager_securityconsole_install_preview":                           resourceSecurityconsoleInstallPreview(),
			"fortimanager_securityconsole_preview_result":                            resourceSecurityconsolePreviewResult(),
			"fortimanager_securityconsole_install_package":                           resourceSecurityconsoleInstallPackage(),
			"fortimanager_securityconsole_install_device":                            resourceSecurityconsoleInstallDevice(),
			"fortimanager_securityconsole_import_dev_objs":                           resourceSecurityconsoleImportDevObjs(),
			"fortimanager_securityconsole_package_commit":                            resourceSecurityconsolePackageCommit(),
			"fortimanager_securityconsole_package_cancel_install":                    resourceSecurityconsolePackageCancelInstall(),
			"fortimanager_securityconsole_package_clone":                             resourceSecurityconsolePackageClone(),
			"fortimanager_securityconsole_package_move":                              resourceSecurityconsolePackageMove(),
			"fortimanager_securityconsole_reinstall_package":                         resourceSecurityconsoleReinstallPackage(),
			"fortimanager_securityconsole_sign_certificate_template":                 resourceSecurityconsoleSignCertificateTemplate(),
			"fortimanager_securityconsole_pblock_clone":                              resourceSecurityconsolePblockClone(),
			"fortimanager_object_webfilter_ftgdlocalcat":                             resourceObjectWebfilterFtgdLocalCat(),
			"fortimanager_object_webfilter_urlfilter":                                resourceObjectWebfilterUrlfilter(),
			"fortimanager_object_webfilter_ftgdlocalrating":                          resourceObjectWebfilterFtgdLocalRating(),
			"fortimanager_object_vpn_certificate_ca":                                 resourceObjectVpnCertificateCa(),
			"fortimanager_object_vpn_certificate_remote":                             resourceObjectVpnCertificateRemote(),
			"fortimanager_object_system_fortiguard":                                  resourceObjectSystemFortiguard(),
			"fortimanager_object_ips_custom":                                         resourceObjectIpsCustom(),
			"fortimanager_object_system_dhcp_server":                                 resourceObjectSystemDhcpServer(),
			"fortimanager_object_firewall_address":                                   resourceObjectFirewallAddress(),
			"fortimanager_object_firewall_address6":                                  resourceObjectFirewallAddress6(),
			"fortimanager_object_firewall_addrgrp":                                   resourceObjectFirewallAddrgrp(),
			"fortimanager_object_user_adgrp":                                         resourceObjectUserAdgrp(),
			"fortimanager_object_user_radius":                                        resourceObjectUserRadius(),
			"fortimanager_object_user_ldap":                                          resourceObjectUserLdap(),
			"fortimanager_object_user_local":                                         resourceObjectUserLocal(),
			"fortimanager_object_user_peer":                                          resourceObjectUserPeer(),
			"fortimanager_object_user_peergrp":                                       resourceObjectUserPeergrp(),
			"fortimanager_object_user_group":                                         resourceObjectUserGroup(),
			"fortimanager_object_firewall_service_custom":                            resourceObjectFirewallServiceCustom(),
			"fortimanager_object_firewall_service_group":                             resourceObjectFirewallServiceGroup(),
			"fortimanager_object_firewall_schedule_onetime":                          resourceObjectFirewallScheduleOnetime(),
			"fortimanager_object_firewall_schedule_recurring":                        resourceObjectFirewallScheduleRecurring(),
			"fortimanager_object_firewall_ippool":                                    resourceObjectFirewallIppool(),
			"fortimanager_object_firewall_vip":                                       resourceObjectFirewallVip(),
			"fortimanager_object_firewall_vipgrp":                                    resourceObjectFirewallVipgrp(),
			"fortimanager_object_firewall_addrgrp6":                                  resourceObjectFirewallAddrgrp6(),
			"fortimanager_object_ips_sensor":                                         resourceObjectIpsSensor(),
			"fortimanager_object_log_customfield":                                    resourceObjectLogCustomField(),
			"fortimanager_object_user_tacacs":                                        resourceObjectUserTacacs(),
			"fortimanager_object_firewall_ldbmonitor":                                resourceObjectFirewallLdbMonitor(),
			"fortimanager_object_application_list":                                   resourceObjectApplicationList(),
			"fortimanager_object_dlp_sensor":                                         resourceObjectDlpSensor(),
			"fortimanager_object_wanopt_peer":                                        resourceObjectWanoptPeer(),
			"fortimanager_object_wanopt_authgroup":                                   resourceObjectWanoptAuthGroup(),
			"fortimanager_object_vpn_ssl_web_portal":                                 resourceObjectVpnSslWebPortal(),
			"fortimanager_object_system_replacemsgimage":                             resourceObjectSystemReplacemsgImage(),
			"fortimanager_object_system_replacemsggroup":                             resourceObjectSystemReplacemsgGroup(),
			"fortimanager_object_firewall_gtp":                                       resourceObjectFirewallGtp(),
			"fortimanager_object_webfilter_content":                                  resourceObjectWebfilterContent(),
			"fortimanager_object_webfilter_contentheader":                            resourceObjectWebfilterContentHeader(),
			"fortimanager_object_firewall_schedule_group":                            resourceObjectFirewallScheduleGroup(),
			"fortimanager_object_firewall_shaper_trafficshaper":                      resourceObjectFirewallShaperTrafficShaper(),
			"fortimanager_object_firewall_shaper_peripshaper":                        resourceObjectFirewallShaperPerIpShaper(),
			"fortimanager_object_vpn_ssl_web_hostchecksoftware":                      resourceObjectVpnSslWebHostCheckSoftware(),
			"fortimanager_object_wirelesscontroller_vap":                             resourceObjectWirelessControllerVap(),
			"fortimanager_object_wirelesscontroller_vapgroup":                        resourceObjectWirelessControllerVapGroup(),
			"fortimanager_object_webfilter_profile":                                  resourceObjectWebfilterProfile(),
			"fortimanager_object_antivirus_profile":                                  resourceObjectAntivirusProfile(),
			"fortimanager_object_firewall_profileprotocoloptions":                    resourceObjectFirewallProfileProtocolOptions(),
			"fortimanager_object_firewall_profilegroup":                              resourceObjectFirewallProfileGroup(),
			"fortimanager_object_voip_profile":                                       resourceObjectVoipProfile(),
			"fortimanager_object_user_fortitoken":                                    resourceObjectUserFortitoken(),
			"fortimanager_object_webproxy_forwardserver":                             resourceObjectWebProxyForwardServer(),
			"fortimanager_object_wirelesscontroller_wtpprofile":                      resourceObjectWirelessControllerWtpProfile(),
			"fortimanager_object_dlp_filepattern":                                    resourceObjectDlpFilepattern(),
			"fortimanager_object_icap_server":                                        resourceObjectIcapServer(),
			"fortimanager_object_icap_profile":                                       resourceObjectIcapProfile(),
			"fortimanager_object_user_fsso":                                          resourceObjectUserFsso(),
			"fortimanager_object_system_smsserver":                                   resourceObjectSystemSmsServer(),
			"fortimanager_object_vpn_certificate_ocspserver":                         resourceObjectVpnCertificateOcspServer(),
			"fortimanager_object_user_passwordpolicy":                                resourceObjectUserPasswordPolicy(),
			"fortimanager_object_user_fssopolling":                                   resourceObjectUserFssoPolling(),
			"fortimanager_object_firewall_ippool6":                                   resourceObjectFirewallIppool6(),
			"fortimanager_object_firewall_vip6":                                      resourceObjectFirewallVip6(),
			"fortimanager_object_firewall_vipgrp6":                                   resourceObjectFirewallVipgrp6(),
			"fortimanager_object_firewall_identitybasedroute":                        resourceObjectFirewallIdentityBasedRoute(),
			"fortimanager_object_wirelesscontroller_widsprofile":                     resourceObjectWirelessControllerWidsProfile(),
			"fortimanager_object_switchcontroller_managedswitch":                     resourceObjectSwitchControllerManagedSwitch(),
			"fortimanager_object_wanopt_profile":                                     resourceObjectWanoptProfile(),
			"fortimanager_object_firewall_multicastaddress":                          resourceObjectFirewallMulticastAddress(),
			"fortimanager_object_firewall_service_category":                          resourceObjectFirewallServiceCategory(),
			"fortimanager_object_system_geoipoverride":                               resourceObjectSystemGeoipOverride(),
			"fortimanager_object_application_custom":                                 resourceObjectApplicationCustom(),
			"fortimanager_object_vpn_ssl_web_realm":                                  resourceObjectVpnSslWebRealm(),
			"fortimanager_object_firewall_vip64":                                     resourceObjectFirewallVip64(),
			"fortimanager_object_firewall_vip46":                                     resourceObjectFirewallVip46(),
			"fortimanager_object_firewall_vipgrp64":                                  resourceObjectFirewallVipgrp64(),
			"fortimanager_object_firewall_vipgrp46":                                  resourceObjectFirewallVipgrp46(),
			"fortimanager_object_webproxy_forwardservergroup":                        resourceObjectWebProxyForwardServerGroup(),
			"fortimanager_object_user_pop3":                                          resourceObjectUserPop3(),
			"fortimanager_object_webproxy_profile":                                   resourceObjectWebProxyProfile(),
			"fortimanager_object_extendercontroller_sim_profile":                     resourceObjectExtenderControllerSimProfile(),
			"fortimanager_object_user_securityexemptlist":                            resourceObjectUserSecurityExemptList(),
			"fortimanager_object_firewall_sslsshprofile":                             resourceObjectFirewallSslSshProfile(),
			"fortimanager_object_system_customlanguage":                              resourceObjectSystemCustomLanguage(),
			"fortimanager_object_system_geoipcountry":                                resourceObjectSystemGeoipCountry(),
			"fortimanager_object_webfilter_categories":                               resourceObjectWebfilterCategories(),
			"fortimanager_object_system_virtualwirepair":                             resourceObjectSystemVirtualWirePair(),
			"fortimanager_object_firewall_multicastaddress6":                         resourceObjectFirewallMulticastAddress6(),
			"fortimanager_object_waf_mainclass":                                      resourceObjectWafMainClass(),
			"fortimanager_object_waf_subclass":                                       resourceObjectWafSubClass(),
			"fortimanager_object_waf_signature":                                      resourceObjectWafSignature(),
			"fortimanager_object_waf_profile":                                        resourceObjectWafProfile(),
			"fortimanager_object_dnsfilter_profile":                                  resourceObjectDnsfilterProfile(),
			"fortimanager_object_webproxy_wisp":                                      resourceObjectWebProxyWisp(),
			"fortimanager_object_user_krbkeytab":                                     resourceObjectUserKrbKeytab(),
			"fortimanager_object_gtp_apn":                                            resourceObjectGtpApn(),
			"fortimanager_object_gtp_apngrp":                                         resourceObjectGtpApngrp(),
			"fortimanager_object_application_categories":                             resourceObjectApplicationCategories(),
			"fortimanager_object_application_group":                                  resourceObjectApplicationGroup(),
			"fortimanager_object_firewall_shapingprofile":                            resourceObjectFirewallShapingProfile(),
			"fortimanager_object_dnsfilter_domainfilter":                             resourceObjectDnsfilterDomainFilter(),
			"fortimanager_object_firewall_internetservice":                           resourceObjectFirewallInternetService(),
			"fortimanager_object_firewall_internetservicecustom":                     resourceObjectFirewallInternetServiceCustom(),
			"fortimanager_object_firewall_proxyaddress":                              resourceObjectFirewallProxyAddress(),
			"fortimanager_object_firewall_proxyaddrgrp":                              resourceObjectFirewallProxyAddrgrp(),
			"fortimanager_object_wirelesscontroller_bonjourprofile":                  resourceObjectWirelessControllerBonjourProfile(),
			"fortimanager_object_switchcontroller_securitypolicy_8021x":              resourceObjectSwitchControllerSecurityPolicy8021X(),
			"fortimanager_object_switchcontroller_lldpprofile":                       resourceObjectSwitchControllerLldpProfile(),
			"fortimanager_object_wirelesscontroller_qosprofile":                      resourceObjectWirelessControllerQosProfile(),
			"fortimanager_object_authentication_scheme":                              resourceObjectAuthenticationScheme(),
			"fortimanager_object_gtp_messagefilterv0v1":                              resourceObjectGtpMessageFilterV0V1(),
			"fortimanager_object_gtp_messagefilterv2":                                resourceObjectGtpMessageFilterV2(),
			"fortimanager_object_gtp_iewhitelist":                                    resourceObjectGtpIeWhiteList(),
			"fortimanager_object_wirelesscontroller_bleprofile":                      resourceObjectWirelessControllerBleProfile(),
			"fortimanager_object_switchcontroller_qos_dot1pmap":                      resourceObjectSwitchControllerQosDot1PMap(),
			"fortimanager_object_switchcontroller_qos_ipdscpmap":                     resourceObjectSwitchControllerQosIpDscpMap(),
			"fortimanager_object_switchcontroller_qos_queuepolicy":                   resourceObjectSwitchControllerQosQueuePolicy(),
			"fortimanager_object_switchcontroller_qos_qospolicy":                     resourceObjectSwitchControllerQosQosPolicy(),
			"fortimanager_object_wirelesscontroller_hotspot20_anqpvenuename":         resourceObjectWirelessControllerHotspot20AnqpVenueName(),
			"fortimanager_object_wirelesscontroller_hotspot20_anqpnetworkauthtype":   resourceObjectWirelessControllerHotspot20AnqpNetworkAuthType(),
			"fortimanager_object_wirelesscontroller_hotspot20_anqproamingconsortium": resourceObjectWirelessControllerHotspot20AnqpRoamingConsortium(),
			"fortimanager_object_wirelesscontroller_hotspot20_anqpnairealm":          resourceObjectWirelessControllerHotspot20AnqpNaiRealm(),
			"fortimanager_object_wirelesscontroller_hotspot20_anqp3gppcellular":      resourceObjectWirelessControllerHotspot20Anqp3GppCellular(),
			"fortimanager_object_wirelesscontroller_hotspot20_anqpipaddresstype":     resourceObjectWirelessControllerHotspot20AnqpIpAddressType(),
			"fortimanager_object_wirelesscontroller_hotspot20_h2qpoperatorname":      resourceObjectWirelessControllerHotspot20H2QpOperatorName(),
			"fortimanager_object_wirelesscontroller_hotspot20_h2qpwanmetric":         resourceObjectWirelessControllerHotspot20H2QpWanMetric(),
			"fortimanager_object_wirelesscontroller_hotspot20_h2qpconncapability":    resourceObjectWirelessControllerHotspot20H2QpConnCapability(),
			"fortimanager_object_wirelesscontroller_hotspot20_h2qposuprovider":       resourceObjectWirelessControllerHotspot20H2QpOsuProvider(),
			"fortimanager_object_wirelesscontroller_hotspot20_qosmap":                resourceObjectWirelessControllerHotspot20QosMap(),
			"fortimanager_object_wirelesscontroller_hotspot20_hsprofile":             resourceObjectWirelessControllerHotspot20HsProfile(),
			"fortimanager_object_system_sdnconnector":                                resourceObjectSystemSdnConnector(),
			"fortimanager_object_user_domaincontroller":                              resourceObjectUserDomainController(),
			"fortimanager_object_system_objecttagging":                               resourceObjectSystemObjectTagging(),
			"fortimanager_object_firewall_address6template":                          resourceObjectFirewallAddress6Template(),
			"fortimanager_object_firewall_wildcardfqdn_custom":                       resourceObjectFirewallWildcardFqdnCustom(),
			"fortimanager_object_firewall_wildcardfqdn_group":                        resourceObjectFirewallWildcardFqdnGroup(),
			"fortimanager_object_firewall_internetservicegroup":                      resourceObjectFirewallInternetServiceGroup(),
			"fortimanager_object_firewall_internetservicecustomgroup":                resourceObjectFirewallInternetServiceCustomGroup(),
			"fortimanager_object_system_externalresource":                            resourceObjectSystemExternalResource(),
			"fortimanager_object_sshfilter_profile":                                  resourceObjectSshFilterProfile(),
			"fortimanager_object_gtp_tunnellimit":                                    resourceObjectGtpTunnelLimit(),
			"fortimanager_object_wirelesscontroller_utmprofile":                      resourceObjectWirelessControllerUtmProfile(),
			"fortimanager_object_firewall_ssh_localca":                               resourceObjectFirewallSshLocalCa(),
			"fortimanager_object_wirelesscontroller_region":                          resourceObjectWirelessControllerRegion(),
			"fortimanager_object_dlp_sensitivity":                                    resourceObjectDlpSensitivity(),
			"fortimanager_object_emailfilter_bword":                                  resourceObjectEmailfilterBword(),
			"fortimanager_object_emailfilter_bwl":                                    resourceObjectEmailfilterBwl(),
			"fortimanager_object_emailfilter_mheader":                                resourceObjectEmailfilterMheader(),
			"fortimanager_object_emailfilter_dnsbl":                                  resourceObjectEmailfilterDnsbl(),
			"fortimanager_object_emailfilter_iptrust":                                resourceObjectEmailfilterIptrust(),
			"fortimanager_object_emailfilter_profile":                                resourceObjectEmailfilterProfile(),
			"fortimanager_object_emailfilter_fortishield":                            resourceObjectEmailfilterFortishield(),
			"fortimanager_object_emailfilter_options":                                resourceObjectEmailfilterOptions(),
			"fortimanager_object_user_exchange":                                      resourceObjectUserExchange(),
			"fortimanager_object_firewall_internetserviceaddition":                   resourceObjectFirewallInternetServiceAddition(),
			"fortimanager_object_cifs_profile":                                       resourceObjectCifsProfile(),
			"fortimanager_object_user_saml":                                          resourceObjectUserSaml(),
			"fortimanager_object_firewall_trafficclass":                              resourceObjectFirewallTrafficClass(),
			"fortimanager_object_wirelesscontroller_wagprofile":                      resourceObjectWirelessControllerWagProfile(),
			"fortimanager_object_credentialstore_domaincontroller":                   resourceObjectCredentialStoreDomainController(),
			"fortimanager_object_wirelesscontroller_apcfgprofile":                    resourceObjectWirelessControllerApcfgProfile(),
			"fortimanager_object_firewall_internetservicename":                       resourceObjectFirewallInternetServiceName(),
			"fortimanager_object_firewall_decryptedtrafficmirror":                    resourceObjectFirewallDecryptedTrafficMirror(),
			"fortimanager_object_filefilter_profile":                                 resourceObjectFileFilterProfile(),
			"fortimanager_object_extendercontroller_dataplan":                        resourceObjectExtenderControllerDataplan(),
			"fortimanager_object_wirelesscontroller_mpskprofile":                     resourceObjectWirelessControllerMpskProfile(),
			"fortimanager_object_dynamic_multicast_interface":                        resourceObjectDynamicMulticastInterface(),
			"fortimanager_object_dynamic_interface":                                  resourceObjectDynamicInterface(),
			"fortimanager_object_dynamic_address":                                    resourceObjectDynamicAddress(),
			"fortimanager_object_vpnmgr_vpntable":                                    resourceObjectVpnmgrVpntable(),
			"fortimanager_object_vpnmgr_node":                                        resourceObjectVpnmgrNode(),
			"fortimanager_object_system_meta":                                        resourceObjectSystemMeta(),
			"fortimanager_object_adom_options":                                       resourceObjectAdomOptions(),
			"fortimanager_object_dynamic_vip":                                        resourceObjectDynamicVip(),
			"fortimanager_object_dynamic_ippool":                                     resourceObjectDynamicIppool(),
			"fortimanager_object_dynamic_certificate_local":                          resourceObjectDynamicCertificateLocal(),
			"fortimanager_object_dynamic_vpntunnel":                                  resourceObjectDynamicVpntunnel(),
			"fortimanager_object_certificate_template":                               resourceObjectCertificateTemplate(),
			"fortimanager_object_dynamic_virtualwanlink_members":                     resourceObjectDynamicVirtualWanLinkMembers(),
			"fortimanager_object_dynamic_virtualwanlink_server":                      resourceObjectDynamicVirtualWanLinkServer(),
			"fortimanager_object_dynamic_virtualwanlink_neighbor":                    resourceObjectDynamicVirtualWanLinkNeighbor(),
			"fortimanager_object_user_pxgrid":                                        resourceObjectUserPxgrid(),
			"fortimanager_object_user_clearpass":                                     resourceObjectUserClearpass(),
			"fortimanager_object_user_nsx":                                           resourceObjectUserNsx(),
			"fortimanager_object_user_vcenter":                                       resourceObjectUserVcenter(),
			"fortimanager_object_cli_template":                                       resourceObjectCliTemplate(),
			"fortimanager_object_cli_templategroup":                                  resourceObjectCliTemplateGroup(),
			"fortimanager_object_fsp_vlan":                                           resourceObjectFspVlan(),
			"fortimanager_system_global":                                             resourceSystemGlobal(),
			"fortimanager_system_global_mcpolicydisabledadoms":                       resourceSystemGlobalMcPolicyDisabledAdoms(),
			"fortimanager_system_interface":                                          resourceSystemInterface(),
			"fortimanager_system_snmp_sysinfo":                                       resourceSystemSnmpSysinfo(),
			"fortimanager_system_snmp_community":                                     resourceSystemSnmpCommunity(),
			"fortimanager_system_snmp_user":                                          resourceSystemSnmpUser(),
			"fortimanager_system_route":                                              resourceSystemRoute(),
			"fortimanager_system_route6":                                             resourceSystemRoute6(),
			"fortimanager_system_dns":                                                resourceSystemDns(),
			"fortimanager_system_connector":                                          resourceSystemConnector(),
			"fortimanager_system_ha":                                                 resourceSystemHa(),
			"fortimanager_system_ha_peer":                                            resourceSystemHaPeer(),
			"fortimanager_system_certificate_ca":                                     resourceSystemCertificateCa(),
			"fortimanager_system_certificate_local":                                  resourceSystemCertificateLocal(),
			"fortimanager_system_certificate_crl":                                    resourceSystemCertificateCrl(),
			"fortimanager_system_certificate_remote":                                 resourceSystemCertificateRemote(),
			"fortimanager_system_certificate_oftp":                                   resourceSystemCertificateOftp(),
			"fortimanager_system_certificate_ssh":                                    resourceSystemCertificateSsh(),
			"fortimanager_system_saml":                                               resourceSystemSaml(),
			"fortimanager_system_saml_fabricidp":                                     resourceSystemSamlFabricIdp(),
			"fortimanager_system_saml_serviceproviders":                              resourceSystemSamlServiceProviders(),
			"fortimanager_system_ntp":                                                resourceSystemNtp(),
			"fortimanager_system_ntp_ntpserver":                                      resourceSystemNtpNtpserver(),
			"fortimanager_system_backup_allsettings":                                 resourceSystemBackupAllSettings(),
			"fortimanager_system_guiact":                                             resourceSystemGuiact(),
			"fortimanager_system_metadata_admins":                                    resourceSystemMetadataAdmins(),
			"fortimanager_system_admin_profile":                                      resourceSystemAdminProfile(),
			"fortimanager_system_admin_radius":                                       resourceSystemAdminRadius(),
			"fortimanager_system_admin_ldap":                                         resourceSystemAdminLdap(),
			"fortimanager_system_admin_tacacs":                                       resourceSystemAdminTacacs(),
			"fortimanager_system_admin_group":                                        resourceSystemAdminGroup(),
			"fortimanager_system_admin_user":                                         resourceSystemAdminUser(),
			"fortimanager_system_admin_setting":                                      resourceSystemAdminSetting(),
			"fortimanager_system_passwordpolicy":                                     resourceSystemPasswordPolicy(),
			"fortimanager_system_alertemail":                                         resourceSystemAlertemail(),
			"fortimanager_system_syslog":                                             resourceSystemSyslog(),
			"fortimanager_system_mail":                                               resourceSystemMail(),
			"fortimanager_system_alertevent":                                         resourceSystemAlertEvent(),
			"fortimanager_system_alertconsole":                                       resourceSystemAlertConsole(),
			"fortimanager_system_locallog_disk_setting":                              resourceSystemLocallogDiskSetting(),
			"fortimanager_system_locallog_disk_filter":                               resourceSystemLocallogDiskFilter(),
			"fortimanager_system_locallog_memory_setting":                            resourceSystemLocallogMemorySetting(),
			"fortimanager_system_locallog_memory_filter":                             resourceSystemLocallogMemoryFilter(),
			"fortimanager_system_locallog_fortianalyzer_filter":                      resourceSystemLocallogFortianalyzerFilter(),
			"fortimanager_system_locallog_fortianalyzer_setting":                     resourceSystemLocallogFortianalyzerSetting(),
			"fortimanager_system_locallog_fortianalyzer2_filter":                     resourceSystemLocallogFortianalyzer2Filter(),
			"fortimanager_system_locallog_fortianalyzer2_setting":                    resourceSystemLocallogFortianalyzer2Setting(),
			"fortimanager_system_locallog_fortianalyzer3_filter":                     resourceSystemLocallogFortianalyzer3Filter(),
			"fortimanager_system_locallog_fortianalyzer3_setting":                    resourceSystemLocallogFortianalyzer3Setting(),
			"fortimanager_system_locallog_syslogd_setting":                           resourceSystemLocallogSyslogdSetting(),
			"fortimanager_system_locallog_syslogd_filter":                            resourceSystemLocallogSyslogdFilter(),
			"fortimanager_system_locallog_syslogd2_setting":                          resourceSystemLocallogSyslogd2Setting(),
			"fortimanager_system_locallog_syslogd2_filter":                           resourceSystemLocallogSyslogd2Filter(),
			"fortimanager_system_locallog_syslogd3_setting":                          resourceSystemLocallogSyslogd3Setting(),
			"fortimanager_system_locallog_syslogd3_filter":                           resourceSystemLocallogSyslogd3Filter(),
			"fortimanager_system_locallog_setting":                                   resourceSystemLocallogSetting(),
			"fortimanager_system_fips":                                               resourceSystemFips(),
			"fortimanager_system_workflow_approvalmatrix":                            resourceSystemWorkflowApprovalMatrix(),
			"fortimanager_system_docker":                                             resourceSystemDocker(),
			"fortimanager_system_sniffer":                                            resourceSystemSniffer(),
			"fortimanager_system_dm":                                                 resourceSystemDm(),
			"fortimanager_system_log_alert":                                          resourceSystemLogAlert(),
			"fortimanager_system_log_interfacestats":                                 resourceSystemLogInterfaceStats(),
			"fortimanager_system_log_ioc":                                            resourceSystemLogIoc(),
			"fortimanager_system_log_maildomain":                                     resourceSystemLogMailDomain(),
			"fortimanager_system_log_devicedisable":                                  resourceSystemLogDeviceDisable(),
			"fortimanager_system_log_settings":                                       resourceSystemLogSettings(),
			"fortimanager_system_log_settings_rollinganalyzer":                       resourceSystemLogSettingsRollingAnalyzer(),
			"fortimanager_system_log_settings_rollinglocal":                          resourceSystemLogSettingsRollingLocal(),
			"fortimanager_system_log_settings_rollingregular":                        resourceSystemLogSettingsRollingRegular(),
			"fortimanager_system_logfetch_serversettings":                            resourceSystemLogFetchServerSettings(),
			"fortimanager_system_logfetch_clientprofile":                             resourceSystemLogFetchClientProfile(),
			"fortimanager_system_sql":                                                resourceSystemSql(),
			"fortimanager_system_sql_tsindexfield":                                   resourceSystemSqlTsIndexField(),
			"fortimanager_system_sql_customskipidx":                                  resourceSystemSqlCustomSkipidx(),
			"fortimanager_system_sql_customindex":                                    resourceSystemSqlCustomIndex(),
			"fortimanager_system_report_estbrowsetime":                               resourceSystemReportEstBrowseTime(),
			"fortimanager_system_report_autocache":                                   resourceSystemReportAutoCache(),
			"fortimanager_system_report_setting":                                     resourceSystemReportSetting(),
			"fortimanager_system_report_group":                                       resourceSystemReportGroup(),
			"fortimanager_system_fortiview_setting":                                  resourceSystemFortiviewSetting(),
			"fortimanager_system_fortiview_autocache":                                resourceSystemFortiviewAutoCache(),
			"fortimanager_system_autodelete":                                         resourceSystemAutoDelete(),
			"fortimanager_system_autodelete_quarantinefilesautodeletion":             resourceSystemAutoDeleteQuarantineFilesAutoDeletion(),
			"fortimanager_system_autodelete_dlpfilesautodeletion":                    resourceSystemAutoDeleteDlpFilesAutoDeletion(),
			"fortimanager_system_autodelete_reportautodeletion":                      resourceSystemAutoDeleteReportAutoDeletion(),
			"fortimanager_system_autodelete_logautodeletion":                         resourceSystemAutoDeleteLogAutoDeletion(),
			"fortimanager_fmupdate_avips_webproxy":                                   resourceFmupdateAvIpsWebProxy(),
			"fortimanager_fmupdate_avips_advancedlog":                                resourceFmupdateAvIpsAdvancedLog(),
			"fortimanager_fmupdate_webspam_webproxy":                                 resourceFmupdateWebSpamWebProxy(),
			"fortimanager_fmupdate_webspam_fgdsetting":                               resourceFmupdateWebSpamFgdSetting(),
			"fortimanager_fmupdate_webspam_fgdsetting_serveroverride":                resourceFmupdateWebSpamFgdSettingServerOverride(),
			"fortimanager_fmupdate_webspam_fgdsetting_serveroverride_servlist":       resourceFmupdateWebSpamFgdSettingServerOverrideServlist(),
			"fortimanager_fmupdate_fctservices":                                      resourceFmupdateFctServices(),
			"fortimanager_fmupdate_analyzer_virusreport":                             resourceFmupdateAnalyzerVirusreport(),
			"fortimanager_fmupdate_service":                                          resourceFmupdateService(),
			"fortimanager_fmupdate_publicnetwork":                                    resourceFmupdatePublicnetwork(),
			"fortimanager_fmupdate_diskquota":                                        resourceFmupdateDiskQuota(),
			"fortimanager_fmupdate_serveraccesspriorities":                           resourceFmupdateServerAccessPriorities(),
			"fortimanager_fmupdate_serveraccesspriorities_privateserver":             resourceFmupdateServerAccessPrioritiesPrivateServer(),
			"fortimanager_fmupdate_customurllist":                                    resourceFmupdateCustomUrlList(),
			"fortimanager_fmupdate_serveroverridestatus":                             resourceFmupdateServerOverrideStatus(),
			"fortimanager_fmupdate_multilayer":                                       resourceFmupdateMultilayer(),
			"fortimanager_fmupdate_fdssetting":                                       resourceFmupdateFdsSetting(),
			"fortimanager_fmupdate_fdssetting_serveroverride":                        resourceFmupdateFdsSettingServerOverride(),
			"fortimanager_fmupdate_fdssetting_serveroverride_servlist":               resourceFmupdateFdsSettingServerOverrideServlist(),
			"fortimanager_fmupdate_fdssetting_updateschedule":                        resourceFmupdateFdsSettingUpdateSchedule(),
			"fortimanager_fmupdate_fdssetting_pushoverridetoclient":                  resourceFmupdateFdsSettingPushOverrideToClient(),
			"fortimanager_fmupdate_fdssetting_pushoverridetoclient_announceip":       resourceFmupdateFdsSettingPushOverrideToClientAnnounceIp(),
			"fortimanager_fmupdate_fdssetting_pushoverride":                          resourceFmupdateFdsSettingPushOverride(),
			"fortimanager_fmupdate_fwmsetting":                                       resourceFmupdateFwmSetting(),
			"fortimanager_dvmdb_device":                                              resourceDvmdbDevice(),
			"fortimanager_dvmdb_group":                                               resourceDvmdbGroup(),
			"fortimanager_dvmdb_script":                                              resourceDvmdbScript(),
			"fortimanager_dvmdb_revision":                                            resourceDvmdbRevision(),
			"fortimanager_dvmdb_folder":                                              resourceDvmdbFolder(),
			"fortimanager_dvmdb_adom":                                                resourceDvmdbAdom(),
		},

		ConfigureFunc: providerConfigure,
	}
}

func providerConfigure(d *schema.ResourceData) (interface{}, error) {
	config := Config{
		Hostname:  d.Get("hostname").(string),
		User:      d.Get("username").(string),
		Passwd:    d.Get("password").(string),
		CABundle:  d.Get("cabundlefile").(string),
		ScopeType: d.Get("scopetype").(string),
		Adom:      d.Get("adom").(string),
	}

	v1, ok1 := d.GetOkExists("insecure")
	if ok1 {
		insecure := v1.(bool)
		config.Insecure = &insecure
	}

	// Create Client for later connections
	return config.CreateClient()
}
